class HabitLibrary {
  static List<Map<String, dynamic>> habitsList = [
    
    {'id': 2, 'name': '10,000 Steps', 'icon': 394, 'category': 0},
    {'id': 3, 'name': 'Wake Up Early', 'icon': 140, 'category': 0},
    {'id': 4, 'name': 'Stretch or Yoga', 'icon': 4, 'category': 0},
    {'id': 5, 'name': 'Read Daily', 'icon': 21, 'category': 0},
    {'id': 0, 'name': 'Meditate Daily', 'icon': 70, 'category': 0},
    {'id': 1, 'name': 'Journal', 'icon': 29, 'category': 0},
    {'id': 6, 'name': 'Plan Your Day', 'icon': 110, 'category': 0},
    {'id': 7, 'name': 'Practice a Hobby', 'icon': 80, 'category': 0},
    {'id': 8, 'name': 'Drink Water', 'icon': 11, 'category': 0},
    {'id': 9, 'name': 'Daily Gratitude', 'icon': 70, 'category': 0},

    {'id': 10, 'name': 'Meditation', 'icon': 39, 'category': 1},
    {'id': 11, 'name': 'Drink Water', 'icon': 11, 'category': 1},
    {'id': 12, 'name': 'Healthy Eating', 'icon': 12, 'category': 1},
    {'id': 13, 'name': 'Early Sleep', 'icon': 5, 'category': 1},
    {'id': 14, 'name': 'Skincare', 'icon': 104, 'category': 1},
    {'id': 15, 'name': 'Take Vitamins', 'icon': 100, 'category': 1},
    {'id': 16, 'name': 'Breathing Exercises', 'icon': 654, 'category': 1},
    {'id': 17, 'name': 'Floss Teeth', 'icon': 101, 'category': 1},
    {'id': 18, 'name': 'Posture Check', 'icon': 310, 'category': 1},
    {'id': 19, 'name': 'Eye Exercises', 'icon': 324, 'category': 1},
    {'id': 20, 'name': 'Cold Shower', 'icon': 1214, 'category': 1},
    {'id': 21, 'name': 'Green Tea', 'icon': 764, 'category': 1},
    {'id': 22, 'name': 'Eat Fruits', 'icon': 10, 'category': 1},
    {'id': 23, 'name': 'Wash Hands', 'icon': 102, 'category': 1},
    {'id': 24, 'name': 'Bath', 'icon': 1215, 'category': 1},

    {'id': 25, 'name': 'Morning Run', 'icon': 1, 'category': 2},
    {'id': 26, 'name': 'Workout Session', 'icon': 0, 'category': 2},
    {'id': 27, 'name': 'Yoga Practice', 'icon': 4, 'category': 2},
    {'id': 28, 'name': 'Swimming', 'icon': 7, 'category': 2},
    {'id': 29, 'name': 'Cycling', 'icon': 6, 'category': 2},
    {'id': 30, 'name': 'Evening Walk', 'icon': 2, 'category': 2},
    {'id': 31, 'name': 'Stretching', 'icon': 8, 'category': 2},
    {'id': 32, 'name': 'Strength Training', 'icon': 3, 'category': 2},
    {'id': 33, 'name': 'Cardio', 'icon': 1, 'category': 2},
    {'id': 34, 'name': 'HIIT Workout', 'icon': 0, 'category': 2},
    {'id': 35, 'name': 'Dance', 'icon': 396, 'category': 2},
    {'id': 36, 'name': 'Pilates', 'icon': 4, 'category': 2},
    {'id': 37, 'name': 'Walking', 'icon': 2, 'category': 2},
    {'id': 38, 'name': 'Home Workout', 'icon': 0, 'category': 2},
    {'id': 39, 'name': 'Jump Rope', 'icon': 8, 'category': 2},

    {'id': 40, 'name': 'Reading', 'icon': 20, 'category': 3},
    {'id': 41, 'name': 'Journaling', 'icon': 29, 'category': 3},
    {'id': 42, 'name': 'Learn Something New', 'icon': 52, 'category': 3},
    {'id': 43, 'name': 'Coding', 'icon': 23, 'category': 3},
    {'id': 44, 'name': 'Practice Language', 'icon': 21, 'category': 3},
    {'id': 45, 'name': 'Listen Podcast', 'icon': 36, 'category': 3},
    {'id': 46, 'name': 'Music Practice', 'icon': 1004, 'category': 3},
    {'id': 47, 'name': 'Drawing', 'icon': 80, 'category': 3},
    {'id': 48, 'name': 'Gratitude Practice', 'icon': 70, 'category': 3},
    {'id': 49, 'name': 'Public Speaking', 'icon': 47, 'category': 3},
    {'id': 50, 'name': 'Creative Time', 'icon': 80, 'category': 3},
    {'id': 51, 'name': 'Read Book', 'icon': 21, 'category': 3},
    {'id': 52, 'name': 'Online Course', 'icon': 58, 'category': 3},
    {'id': 53, 'name': 'Positive Thinking', 'icon': 34, 'category': 3},
    {'id': 54, 'name': 'Self Love', 'icon': 275, 'category': 3},

    {'id': 55, 'name': 'Wake Up Early', 'icon': 140, 'category': 4},
    {'id': 56, 'name': 'Goal Setting', 'icon': 24, 'category': 4},
    {'id': 57, 'name': 'Plan the Day', 'icon': 110, 'category': 4},
    {'id': 58, 'name': 'Pomodoro Technique', 'icon': 26, 'category': 4},
    {'id': 59, 'name': 'Time Blocking', 'icon': 144, 'category': 4},
    {'id': 60, 'name': 'Track Progress', 'icon': 127, 'category': 4},
    {'id': 61, 'name': 'Weekly Review', 'icon': 111, 'category': 4},
    {'id': 62, 'name': 'Calendar Review', 'icon': 144, 'category': 4},
    {'id': 63, 'name': 'Deep Work', 'icon': 23, 'category': 4},
    {'id': 64, 'name': 'Task Prioritization', 'icon': 24, 'category': 4},
    {'id': 65, 'name': 'Daily Planning', 'icon': 110, 'category': 4},
    {'id': 66, 'name': 'Focus Sessions', 'icon': 147, 'category': 4},
    {'id': 67, 'name': 'Goal Review', 'icon': 111, 'category': 4},
    {'id': 68, 'name': 'Limit Distractions', 'icon': 63, 'category': 4},
    {'id': 69, 'name': 'Achievement Tracking', 'icon': 127, 'category': 4},

    {'id': 85, 'name': 'Procrastination', 'icon': 200, 'category': 5},
    {'id': 87, 'name': 'Overthinking', 'icon': 183, 'category': 5},
    {'id': 88, 'name': 'Late Night Snacking', 'icon': 19, 'category': 5},
    {'id': 89, 'name': 'Social Media Scrolling', 'icon': 38, 'category': 5},
    {'id': 90, 'name': 'Negative Self-Talk', 'icon': 221, 'category': 5},
    {'id': 91, 'name': 'Impulse Buying', 'icon': 64, 'category': 5},
    {'id': 92, 'name': 'Emotional Eating', 'icon': 19, 'category': 5},
    {'id': 93, 'name': 'Gossiping', 'icon': 179, 'category': 5},
    {'id': 94, 'name': 'Skipping Breakfast', 'icon': 14, 'category': 5},
    {'id': 95, 'name': 'Complaining', 'icon': 193, 'category': 5},
    {'id': 96, 'name': 'Mindless Scrolling', 'icon': 38, 'category': 5},
    {'id': 97, 'name': 'Sitting Too Long', 'icon': 244, 'category': 5},
    {'id': 98, 'name': 'Swearing', 'icon': 248, 'category': 5},
    {'id': 99, 'name': 'Workaholism', 'icon': 23, 'category': 5},
    {'id': 100, 'name': 'Reduce Sugar Intake', 'icon': 19, 'category': 5},
    {'id': 101, 'name': 'Reduce Smoking', 'icon': 1283, 'category': 5},
  ];
}