class HabitLibrary {
  static List<Map<String, dynamic>> habitsList = [
    {'id': 0, 'name': 'Morning Run', 'icon': 0, 'category': 1},
    {'id': 1, 'name': 'Workout Session', 'icon': 1, 'category': 1},
    {'id': 2, 'name': 'Meditation', 'icon': 2, 'category': 0},
    {'id': 3, 'name': 'Reading', 'icon': 3, 'category': 2},
    {'id': 4, 'name': 'Journaling', 'icon': 4, 'category': 2},
    {'id': 5, 'name': 'Drink Water', 'icon': 5, 'category': 0},
    {'id': 6, 'name': 'Healthy Eating', 'icon': 6, 'category': 0},
    {'id': 7, 'name': 'Early Sleep', 'icon': 7, 'category': 0},
    {'id': 8, 'name': 'Wake Up Early', 'icon': 8, 'category': 3},
    {'id': 9, 'name': 'Learn Something New', 'icon': 9, 'category': 2},
    {'id': 10, 'name': 'Goal Setting', 'icon': 10, 'category': 3},
    {'id': 11, 'name': 'Digital Detox', 'icon': 11, 'category': 4},
    {'id': 12, 'name': 'Evening Walk', 'icon': 12, 'category': 1},
    {'id': 13, 'name': 'No Smoking', 'icon': 13, 'category': 4},
    {'id': 14, 'name': 'No Alcohol', 'icon': 14, 'category': 4},
    {'id': 15, 'name': 'Eat Fruits', 'icon': 15, 'category': 0},
    {'id': 16, 'name': 'No Sugary Drinks', 'icon': 16, 'category': 4},
    {'id': 17, 'name': 'Cleaning', 'icon': 17, 'category': 2},
    {'id': 18, 'name': 'Plan Day', 'icon': 18, 'category': 3},
    {'id': 19, 'name': 'Save Money', 'icon': 19, 'category': 2},
    {'id': 20, 'name': 'Yoga Practice', 'icon': 20, 'category': 1},
    {'id': 21, 'name': 'Swimming', 'icon': 21, 'category': 1},
    {'id': 22, 'name': 'Cycling', 'icon': 22, 'category': 1},
    {'id': 23, 'name': 'Practice Music', 'icon': 23, 'category': 2},
    {'id': 24, 'name': 'Drawing', 'icon': 24, 'category': 2},
    {'id': 25, 'name': 'Read Book', 'icon': 25, 'category': 2},
    {'id': 26, 'name': 'Practice Language', 'icon': 26, 'category': 2},
    {'id': 27, 'name': 'Math Practice', 'icon': 27, 'category': 2},
    {'id': 28, 'name': 'Coding', 'icon': 28, 'category': 2},
    {'id': 29, 'name': 'Review Finances', 'icon': 29, 'category': 2},
    {'id': 30, 'name': 'Skincare', 'icon': 30, 'category': 0},
    {'id': 31, 'name': 'Cold Shower', 'icon': 31, 'category': 0},
    {'id': 32, 'name': 'Floss Teeth', 'icon': 32, 'category': 0},
    {'id': 33, 'name': 'Wash Hands', 'icon': 33, 'category': 0},
    {'id': 34, 'name': 'Laundry', 'icon': 34, 'category': 2},
    {'id': 35, 'name': 'Cook Meal', 'icon': 35, 'category': 2},
    {'id': 36, 'name': 'No Soda', 'icon': 36, 'category': 4},
    {'id': 37, 'name': 'No Junk Food', 'icon': 37, 'category': 4},
    {'id': 38, 'name': 'Limit Coffee', 'icon': 38, 'category': 4},
    {'id': 39, 'name': 'Green Tea', 'icon': 39, 'category': 0},
    {'id': 40, 'name': 'Take Vitamins', 'icon': 40, 'category': 0},
    {'id': 41, 'name': 'Watch Sunrise', 'icon': 41, 'category': 2},
    {'id': 42, 'name': 'Sunset Walk', 'icon': 42, 'category': 2},
    {'id': 43, 'name': 'Nature Time', 'icon': 43, 'category': 2},
    {'id': 44, 'name': 'Walk Dog', 'icon': 44, 'category': 2},
    {'id': 45, 'name': 'Posture Check', 'icon': 45, 'category': 0},
    {'id': 46, 'name': 'Eye Exercises', 'icon': 46, 'category': 0},
    {'id': 47, 'name': 'Breathing Exercises', 'icon': 47, 'category': 0},
    {'id': 48, 'name': 'No Phone in Bed', 'icon': 48, 'category': 4},
    {'id': 49, 'name': 'No Snooze', 'icon': 49, 'category': 3},
    {'id': 50, 'name': 'Bath', 'icon': 50, 'category': 0},
    {'id': 51, 'name': 'Creative Time', 'icon': 51, 'category': 2},
    {'id': 52, 'name': 'DIY Project', 'icon': 52, 'category': 2},
    {'id': 53, 'name': 'Sewing', 'icon': 53, 'category': 2},
    {'id': 54, 'name': 'Gardening', 'icon': 54, 'category': 2},
    {'id': 55, 'name': 'Feed Pets', 'icon': 55, 'category': 2},
    {'id': 56, 'name': 'Declutter', 'icon': 56, 'category': 2},
    {'id': 57, 'name': 'Organize', 'icon': 57, 'category': 2},
    {'id': 58, 'name': 'Grocery Shopping', 'icon': 58, 'category': 2},
    {'id': 59, 'name': 'Meal Prep', 'icon': 59, 'category': 2},
    {'id': 60, 'name': 'Makeup Routine', 'icon': 60, 'category': 2},
    {'id': 61, 'name': 'Hair Care', 'icon': 61, 'category': 2},
    {'id': 62, 'name': 'Plan Outfit', 'icon': 62, 'category': 2},
    {'id': 63, 'name': 'Wear Sneakers', 'icon': 63, 'category': 2},
    {'id': 64, 'name': 'Car Maintenance', 'icon': 64, 'category': 2},
    {'id': 65, 'name': 'Bike Maintenance', 'icon': 65, 'category': 2},
    {'id': 66, 'name': 'Home Repair', 'icon': 66, 'category': 2},
    {'id': 67, 'name': 'Water Plants', 'icon': 67, 'category': 2},
    {'id': 68, 'name': 'Pomodoro Technique', 'icon': 68, 'category': 3},
    {'id': 69, 'name': 'Time Blocking', 'icon': 69, 'category': 3},
    {'id': 70, 'name': 'Calendar Review', 'icon': 70, 'category': 3},
    {'id': 71, 'name': 'Online Course', 'icon': 71, 'category': 2},
    {'id': 72, 'name': 'Read News', 'icon': 72, 'category': 2},
    {'id': 73, 'name': 'Listen Podcast', 'icon': 73, 'category': 2},
    {'id': 74, 'name': 'Listen Music', 'icon': 74, 'category': 2},
    {'id': 75, 'name': 'Gaming Time', 'icon': 75, 'category': 2},
    {'id': 76, 'name': 'Watch Movie', 'icon': 76, 'category': 2},
    {'id': 77, 'name': 'TV Time Limit', 'icon': 77, 'category': 4},
    {'id': 78, 'name': 'Socialize', 'icon': 78, 'category': 2},
    {'id': 79, 'name': 'Call Family', 'icon': 79, 'category': 2},
    {'id': 80, 'name': 'Send Message', 'icon': 80, 'category': 2},
    {'id': 81, 'name': 'Random Act Kindness', 'icon': 81, 'category': 2},
    {'id': 82, 'name': 'Gratitude Practice', 'icon': 82, 'category': 2},
    {'id': 83, 'name': 'Positive Thinking', 'icon': 83, 'category': 2},
    {'id': 84, 'name': 'No Complaining', 'icon': 84, 'category': 4},
    {'id': 85, 'name': 'Smile More', 'icon': 85, 'category': 2},
    {'id': 86, 'name': 'Hug Someone', 'icon': 86, 'category': 2},
    {'id': 87, 'name': 'Public Speaking', 'icon': 87, 'category': 2},
    {'id': 88, 'name': 'Active Listening', 'icon': 88, 'category': 2},
    {'id': 89, 'name': 'Critical Thinking', 'icon': 89, 'category': 2},
    {'id': 90, 'name': 'Puzzle Solving', 'icon': 90, 'category': 2},
    {'id': 91, 'name': 'Play Board Games', 'icon': 91, 'category': 2},
    {'id': 92, 'name': 'Chess', 'icon': 92, 'category': 2},
    {'id': 93, 'name': 'Track Progress', 'icon': 93, 'category': 3},
    {'id': 94, 'name': 'Weekly Review', 'icon': 94, 'category': 3},
    {'id': 95, 'name': 'Habit Streak', 'icon': 95, 'category': 3},
    {'id': 96, 'name': 'Achievement', 'icon': 96, 'category': 3},
    {'id': 97, 'name': 'Goal Completed', 'icon': 97, 'category': 3},
    {'id': 98, 'name': 'Celebrate', 'icon': 98, 'category': 2},
    {'id': 99, 'name': 'Self Love', 'icon': 99, 'category': 2},
  ];
}