class HabitLibrary {
  static List<Map<String, dynamic>> habitsList = [
    // --- CATEGORY 0: Health & Wellness (15 most relevant) ---
    {'id': 0, 'name': 'Meditation', 'icon': 2, 'category': 0},
    {'id': 1, 'name': 'Drink Water', 'icon': 5, 'category': 0},
    {'id': 2, 'name': 'Healthy Eating', 'icon': 6, 'category': 0},
    {'id': 3, 'name': 'Early Sleep', 'icon': 7, 'category': 0},
    {'id': 4, 'name': 'Skincare', 'icon': 30, 'category': 0},
    {'id': 5, 'name': 'Take Vitamins', 'icon': 40, 'category': 0},
    {'id': 6, 'name': 'Breathing Exercises', 'icon': 47, 'category': 0},
    {'id': 7, 'name': 'Floss Teeth', 'icon': 32, 'category': 0},
    {'id': 8, 'name': 'Posture Check', 'icon': 45, 'category': 0},
    {'id': 9, 'name': 'Eye Exercises', 'icon': 46, 'category': 0},
    {'id': 10, 'name': 'Cold Shower', 'icon': 31, 'category': 0},
    {'id': 11, 'name': 'Green Tea', 'icon': 39, 'category': 0},
    {'id': 12, 'name': 'Eat Fruits', 'icon': 15, 'category': 0},
    {'id': 13, 'name': 'Wash Hands', 'icon': 33, 'category': 0},
    {'id': 14, 'name': 'Bath', 'icon': 50, 'category': 0},

    // --- CATEGORY 1: Exercise & Fitness (15 most relevant) ---
    {'id': 15, 'name': 'Morning Run', 'icon': 0, 'category': 1},
    {'id': 16, 'name': 'Workout Session', 'icon': 1, 'category': 1},
    {'id': 17, 'name': 'Yoga Practice', 'icon': 20, 'category': 1},
    {'id': 18, 'name': 'Swimming', 'icon': 21, 'category': 1},
    {'id': 19, 'name': 'Cycling', 'icon': 22, 'category': 1},
    {'id': 20, 'name': 'Evening Walk', 'icon': 12, 'category': 1},
    {'id': 21, 'name': 'Stretching', 'icon': 20, 'category': 1},
    {'id': 22, 'name': 'Strength Training', 'icon': 1, 'category': 1},
    {'id': 23, 'name': 'Cardio', 'icon': 0, 'category': 1},
    {'id': 24, 'name': 'HIIT Workout', 'icon': 1, 'category': 1},
    {'id': 25, 'name': 'Dance', 'icon': 23, 'category': 1},
    {'id': 26, 'name': 'Pilates', 'icon': 20, 'category': 1},
    {'id': 27, 'name': 'Walking', 'icon': 12, 'category': 1},
    {'id': 28, 'name': 'Home Workout', 'icon': 1, 'category': 1},
    {'id': 29, 'name': 'Jump Rope', 'icon': 1, 'category': 1},
    // --- CATEGORY 2: Learning & Personal Growth (15 most relevant) ---
    {'id': 30, 'name': 'Reading', 'icon': 3, 'category': 2},
    {'id': 31, 'name': 'Journaling', 'icon': 4, 'category': 2},
    {'id': 32, 'name': 'Learn Something New', 'icon': 9, 'category': 2},
    {'id': 33, 'name': 'Coding', 'icon': 28, 'category': 2},
    {'id': 34, 'name': 'Practice Language', 'icon': 26, 'category': 2},
    {'id': 35, 'name': 'Listen Podcast', 'icon': 73, 'category': 2},
    {'id': 36, 'name': 'Music Practice', 'icon': 23, 'category': 2},
    {'id': 37, 'name': 'Drawing', 'icon': 24, 'category': 2},
    {'id': 38, 'name': 'Gratitude Practice', 'icon': 82, 'category': 2},
    {'id': 39, 'name': 'Public Speaking', 'icon': 87, 'category': 2},
    {'id': 40, 'name': 'Creative Time', 'icon': 51, 'category': 2},
    {'id': 41, 'name': 'Read Book', 'icon': 25, 'category': 2},
    {'id': 42, 'name': 'Online Course', 'icon': 71, 'category': 2},
    {'id': 43, 'name': 'Positive Thinking', 'icon': 83, 'category': 2},
    {'id': 44, 'name': 'Self Love', 'icon': 99, 'category': 2},

    // --- CATEGORY 3: Productivity & Planning (15 most relevant) ---
    {'id': 45, 'name': 'Wake Up Early', 'icon': 8, 'category': 3},
    {'id': 46, 'name': 'Goal Setting', 'icon': 10, 'category': 3},
    {'id': 47, 'name': 'Plan the Day', 'icon': 18, 'category': 3},
    {'id': 48, 'name': 'Pomodoro Technique', 'icon': 68, 'category': 3},
    {'id': 49, 'name': 'Time Blocking', 'icon': 69, 'category': 3},
    {'id': 50, 'name': 'Track Progress', 'icon': 93, 'category': 3},
    {'id': 51, 'name': 'Weekly Review', 'icon': 94, 'category': 3},
    {'id': 52, 'name': 'Calendar Review', 'icon': 70, 'category': 3},
    {'id': 53, 'name': 'Don\'t Snooze', 'icon': 49, 'category': 3},
    {'id': 54, 'name': 'Task Prioritization', 'icon': 10, 'category': 3},
    {'id': 55, 'name': 'Daily Planning', 'icon': 18, 'category': 3},
    {'id': 56, 'name': 'Focus Sessions', 'icon': 68, 'category': 3},
    {'id': 57, 'name': 'Goal Review', 'icon': 94, 'category': 3},
    {'id': 58, 'name': 'Habit Streak', 'icon': 95, 'category': 3},
    {'id': 59, 'name': 'Achievement Tracking', 'icon': 96, 'category': 3},

    // --- CATEGORY 4: Reducing Bad Habits (15 most relevant) ---
    {'id': 60, 'name': 'Digital Detox', 'icon': 11, 'category': 4},
    {'id': 61, 'name': 'No Smoking', 'icon': 13, 'category': 4},
    {'id': 62, 'name': 'No Alcohol', 'icon': 14, 'category': 4},
    {'id': 63, 'name': 'No Sugary Drinks', 'icon': 16, 'category': 4},
    {'id': 64, 'name': 'No Junk Food', 'icon': 37, 'category': 4},
    {'id': 65, 'name': 'Limit Coffee', 'icon': 38, 'category': 4},
    {'id': 66, 'name': 'No Phone in Bed', 'icon': 48, 'category': 4},
    {'id': 67, 'name': 'TV Time Limit', 'icon': 77, 'category': 4},
    {'id': 68, 'name': 'No Complaining', 'icon': 84, 'category': 4},
    {'id': 69, 'name': 'No Soda', 'icon': 36, 'category': 4},
    {'id': 70, 'name': 'Screen Time Limit', 'icon': 11, 'category': 4},
    {'id': 71, 'name': 'Reduce Social Media', 'icon': 11, 'category': 4},
    {'id': 72, 'name': 'Mindful Eating', 'icon': 6, 'category': 4},
    {'id': 73, 'name': 'Avoid Procrastination', 'icon': 69, 'category': 4},
    {'id': 74, 'name': 'Stress Management', 'icon': 2, 'category': 4},
    // --- CATEGORY 5: Quit Habits (15 most relevant) ---
    {'id': 75, 'name': 'Procrastination', 'icon': 69, 'category': 5},
    {'id': 76, 'name': 'Nail Biting', 'icon': 292, 'category': 5},
    {'id': 77, 'name': 'Overthinking', 'icon': 200, 'category': 5},
    {'id': 78, 'name': 'Late Night Snacking', 'icon': 120, 'category': 5},
    {'id': 79, 'name': 'Social Media Scrolling', 'icon': 11, 'category': 5},
    {'id': 80, 'name': 'Negative Self-Talk', 'icon': 291, 'category': 5},
    {'id': 81, 'name': 'Impulse Buying', 'icon': 58, 'category': 5},
    {'id': 82, 'name': 'Emotional Eating', 'icon': 381, 'category': 5},
    {'id': 83, 'name': 'Gossiping', 'icon': 87, 'category': 5},
    {'id': 84, 'name': 'Skipping Breakfast', 'icon': 353, 'category': 5},
    {'id': 85, 'name': 'Complaining', 'icon': 84, 'category': 5},
    {'id': 86, 'name': 'Mindless Scrolling', 'icon': 11, 'category': 5},
    {'id': 87, 'name': 'Sitting Too Long', 'icon': 45, 'category': 5},
    {'id': 88, 'name': 'Swearing', 'icon': 297, 'category': 5},
    {'id': 89, 'name': 'Workaholism', 'icon': 28, 'category': 5},
  ];
}
